global using System;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using MovieAPI.DTO.Category;
global using MovieAPI.DTO.Director;
global using MovieAPI.DTO.Movie;
global using MovieAPI.DTO.MovieImage;
global using MovieAPI.DTO.Player;
global using MovieAPI.DTO.Platform;
global using MovieAPI.Infrastructure.Data.Context;
global using MovieAPI.Infrastructure.Data.Entities.Category;
global using MovieAPI.Infrastructure.Data.Entities.Platform;
global using MovieAPI.Infrastructure.Data.Entities.Movie;
global using MovieAPI.Infrastructure.Data.Entities.MovieImage;
global using MovieAPI.FileRename;
global using static MovieAPI.DTO.ResponseModelDTO;
global using MovieAPI.Infrastructure.Data.Entities.Player;
global using MovieAPI.Infrastructure.Data.Entities.Director;
global using MovieAPI.Infrastructure.Data.Base;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using MovieAPI.Infrastructure.Data.Entities.App;

